name: CI Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t html-front:ci .

      - name: Run Docker container
        run: docker run -d --name html-container html-front:ci

      - name: Verify Docker container is running
        run: docker ps -a

      - name: Check container logs
        run: docker logs html-container

      - name: Stop and remove Docker container
        run: |
          docker stop html-container
          docker rm html-container

      - name: Validate process success
        run: echo "All processes completed successfully."