name: CI Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      
      name: Check out code
            uses: actions/checkout@v3

            
      name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3

            
      name: Build Docker image
            run: docker build -t html-front:ci .

            
      name: Verify Docker image
            run: docker run --rm html-front:ci